### ISSUE TITLE
cm-13.0: Audio issues

### ISSUE THREAD

**Issue by diepquynh** [diepquynh/android_device_samsung_grandprimeve3g#12]
1. The audio out from earphones jack to small speakers is too quiet at maximum volume
2. There's no bass sound with dual speakers (like F&D or Microlab)

**Comment by koquantam** [comment]
Well, it must be the limitation of Google's SW codecs audio channels. We don't have hardware audio codecs too. Needs more investigations

**Comment by diepquynh** [comment]
~~Hardware limitation confirmed~~

**Comment by diepquynh** [comment]
Fixed by this commit: https://github.com/koquantam/android_device_samsung_scx30g_v2-common/commit/2f6af1b0e6ba8eb7e5638dd1a57cc1329645c993
