### ISSUE TITLE
How to compile cm13 with prebuilt kernel?

### ISSUE THREAD

**Issue by parthibx24** [diepquynh/android_device_samsung_grandprimeve3g#17]
I am trying to compile Lineage13 with prebuilt kernel.but getting this type of errors.

../out/target/product/grandprimeve3g/obj/KERNEL_OBJ/usr', needed by `../out/target/product/grandprimeve3g/obj/SHARED_LIBRARIES/.. '

do i need to add any patch?i didn't added any patch in the source..

**Comment by diepquynh** [comment]
Don't build ROMs with prebuilt kernel, because kernel headers can't be detected during build process when building HALs

**Comment by parthibx24** [comment]
and what about patches? do I need to add any patch on the source?

**Comment by bill-mccoy** [comment]
@Parthib24 There are no patches to make in the Android source as Remilia15 moved all the patches to the device sources

**Comment by parthibx24** [comment]
ooh.ok
thanks for the info.

**Comment by parthibx24** [comment]
now i am getting this error.
--
hardware/sprd/hwcomposer/sc8830/sc8830/gsp_hal.cpp: In function 'int32_t gsp_hal_trigger(int32_t)':
hardware/sprd/hwcomposer/sc8830/sc8830/gsp_hal.cpp:678:25: error: 'GSP_IO_TRIGGER_RUN' was not declared in this scope
     ret = ioctl(gsp_fd, GSP_IO_TRIGGER_RUN, 1);
                         ^
hardware/sprd/hwcomposer/sc8830/sc8830/gsp_hal.cpp: In function 'int32_t gsp_hal_waitdone(int32_t)':
hardware/sprd/hwcomposer/sc8830/sc8830/gsp_hal.cpp:705:25: error: 'GSP_IO_WAIT_FINISH' was not declared in this scope
     ret = ioctl(gsp_fd, GSP_IO_WAIT_FINISH, 1);

**Comment by diepquynh** [comment]
This commit
https://github.com/remilia15/android_kernel_samsung_sprd-RZ/commit/0f672ca60a924e2ea634f691665db57260d440c7

**Comment by parthibx24** [comment]
ok

**Comment by parthibx24** [comment]
Thanks it successfully compiled.
![screenshot-65](https://user-images.githubusercontent.com/22051980/29876415-863b6d78-8dbe-11e7-90f9-8258d52340e5.png)
