### ISSUE TITLE
cm-12.1: Wifi doesn't work

### ISSUE THREAD

**Issue by diepquynh** [diepquynh/android_device_samsung_grandprimeve3g#2]
It only work on first start, then when we disable it, then enable it, it's dead until we remove /data/misc/wifi folder. Logcat:
`I/wpa_supplicant(  901): rfkill: Cannot open RFKILL control device`
`E/wpa_supplicant(  901): Could not read interface p2p-dev-wlan0 flags: No such device`

**Comment by diepquynh** [comment]
@ngoquang2708
Any ideas bro?

**Comment by ngoquang2708** [comment]
What is permission of `/data/misc/wifi` folder before and after reboot? Are they both the same?

**Comment by diepquynh** [comment]
Yes they're. Here I just disable then re-enable WiFi, it dies

**Comment by ngoquang2708** [comment]
The `rfkill` part is not importance. The importance one  is that  why `wpa_supplicant` cannot detect  `p2p-dev-wlan0` device.

**Comment by ngoquang2708** [comment]
What is the permission anyway?

**Comment by diepquynh** [comment]
It seems the problem comes from the source itself, because WiFi still working properly with my CM13 with the same configuration

**Comment by diepquynh** [comment]
And the same for you with WiFi direct before

**Comment by diepquynh** [comment]
![screenshot_2016-10-01-17-46-25](https://cloud.githubusercontent.com/assets/13411810/19013581/17e71b30-87ff-11e6-858f-4103b10bda4b.png)

**Comment by ngoquang2708** [comment]
What about the permission of the `/data/misc/wifi` directory?

**Comment by diepquynh** [comment]
![screenshot_2016-10-01-17-51-12](https://cloud.githubusercontent.com/assets/13411810/19013595/b83305f4-87ff-11e6-8190-04c06e9ead1a.png)

**Comment by ngoquang2708** [comment]
Okay, it seems normal, so what...?

**Comment by diepquynh** [comment]
I have to delete /data/misc/folder to make WiFi work once I disable it or reboot the phone

**Comment by ngoquang2708** [comment]
Have you tried this: reboot to recovery, remove all the contents of the wifi folder, then set permission for it, then reboot.

**Comment by ngoquang2708** [comment]
I got this issue in CM14 too, but not on AOSP7. But instead of dead, the wifi crash the system. I don't know why.

**Comment by diepquynh** [comment]
OK, let me try

**Comment by diepquynh** [comment]
Set the permissions like the above screenshot right?

**Comment by ngoquang2708** [comment]
Yes

2016-10-01 18:30 GMT+07:00 Nguyễn Tuấn Quyền notifications@github.com:

**Comment by diepquynh** [comment]
OK this method doesn't work for me

**Comment by ngoquang2708** [comment]
OK. Can I get full logcat before and after wifi is enabled?

**Comment by diepquynh** [comment]
Here's the one after fully booted, and connected to a network
[wifi.txt](https://github.com/koquantam/android_device_samsung_grandprimeve3g/files/504333/wifi.txt)

**Comment by diepquynh** [comment]
And the one after disabled, then re-enabled WiFi
[wifi2.txt](https://github.com/koquantam/android_device_samsung_grandprimeve3g/files/504335/wifi2.txt)

**Comment by diepquynh** [comment]
Fixed by this commit: https://github.com/koquantam/android_device_samsung_grandprimeve3g/commit/2f2dc0e5f5c2555a50938076a3f71d6b9ecb734e
