### ISSUE TITLE
cm-12.1: Sensors don't work

### ISSUE THREAD

**Issue by diepquynh** [diepquynh/android_device_samsung_grandprimeve3g#3]
Haven't found a logcat for this, but it's completely dead even when playing games like Asphalt 8

**Comment by diepquynh** [comment]
Confirmed via CPU-Z: All sensors aren't working

**Comment by ngoquang2708** [comment]
`strings your-hal-module | grep lib` to see what library it using. I guess that.

**Comment by diepquynh** [comment]
Let's see if that works. I found libyasalgo from stock sensors.sc8830.so

**Comment by diepquynh** [comment]
Thanks, I got it, due to missing blob
