### ISSUE TITLE
cm-12.1: RIL-related issues

### ISSUE THREAD

**Issue by diepquynh** [diepquynh/android_device_samsung_grandprimeve3g#6]
1. There's no call timer
2. Can't receive calls
   logcat: [receivecallstock.txt](https://github.com/koquantam/android_device_samsung_grandprimeve3g/files/513094/receivecall.txt)  [receivecallcm.txt](https://github.com/koquantam/android_device_samsung_grandprimeve3g/files/513120/receivecallcm.txt)
3. InCallUI keeps hanging (still can hear beep sound) when we stop the call
   logcat: [callstock.txt](https://github.com/koquantam/android_device_samsung_grandprimeve3g/files/513095/call.txt) [callcm.txt](https://github.com/koquantam/android_device_samsung_grandprimeve3g/files/513128/callcm.txt)

**Comment by diepquynh** [comment]
@ngoquang2708 Can you have a check? First thing I see when receiving calls is these lines
`W/RILJ    ( 1359): [3946]< GET_CURRENT_CALLS exception, possible invalid RIL response`
`W/RILJ    ( 1359): com.android.internal.telephony.ATParseEx: illegal presentation 3670067`
`W/RILJ    ( 1359):     at com.android.internal.telephony.DriverCall.presentationFromCLIP(DriverCall.java:142)`
`W/RILJ    ( 1359):     at com.android.internal.telephony.SamsungSPRDRIL.responseCallList(SamsungSPRDRIL.java:405)`
`W/RILJ    ( 1359):     at com.android.internal.telephony.SamsungSPRDRIL.processSolicited(SamsungSPRDRIL.java:205)`
`W/RILJ    ( 1359):     at com.android.internal.telephony.RIL.processResponse(RIL.java:2605)`
`W/RILJ    ( 1359):     at com.android.internal.telephony.RIL$RILReceiver.run(RIL.java:605)`
`W/RILJ    ( 1359):     at java.lang.Thread.run(Thread.java:818)`

**Comment by ngoquang2708** [comment]
Try remove `processSolicited()` method. I will do some checks.

**Comment by ngoquang2708** [comment]
Where is the vendor repo for this device? Can you post the result of the following command:

```
strings libreference-ril_sp.so | grep gsm
```

**Comment by diepquynh** [comment]
Here's the vendor tree: https://github.com/koquantam/android_vendor_samsung_grandprimeve3g
And the command:
`Sril_GetgsmamrWideband`
`Sril_GetgsmamrNarrowband`
`gsm.operator.numeric`
`gsm.sim.operator.numeric`
`[%c] gsm7bit : %d`
`[%c] set sim2 to gsm only`
`[%c] set sim1 to gsm only`
`[%c] Set sim1 to auto sim2 to gsm only cmd is:%s`
`[%c] change master card to gsm only`
`gsm.network.type`
`gsm.network.type2`
`[RIL::FD] gsm.operator.numeric`
`[RIL::FD] gsm.operator.numeric2`
`Sril_GetgsmamrWideband`
`Sril_GetgsmamrNarrowband`

**Comment by diepquynh** [comment]
Fixed by this: https://github.com/koquantam/android_device_samsung_grandprimeve3g/commit/75b324ee50a7aa03e6f806f144fc8a3c4f585cb8
