### ISSUE TITLE
[SM-G531H][CM13.0] Can't change 2G instead of 3G

### ISSUE THREAD

**Issue by eldoctor94** [diepquynh/android_device_samsung_grandprimeve3g#8]
I Have found a problem when I try to change the network connectivity from 3G to 2G, to any SIMCARD. I suppose **NetworkSettings** service would be the causant of that problem, i saw an exception in some line.. I've enclosed the logcat with only that service that I suppose would be the problem... Also I have tried using the famous code _#_#4636#_#_ but stills...

[net-dont-change.txt](https://github.com/koquantam/android_device_samsung_grandprimeve3g/files/542867/net-dont-change.txt)

10-20 14:38:50.688 I/ActivityManager(856): START u0 {cmp=com.android.phone/.MobileNetworkSettings (has extras)} from uid 1000 on display 0
10-20 14:38:50.737 D/NetworkSettings(2147): onCreate:+
10-20 14:38:50.857 D/NetworkSettings(2147): initializeSubscriptions:+
10-20 14:38:50.885 D/NetworkSettings(2147): isUpdateTabsNeeded:- DO_NOTHING newSil.size()=1 mActiveSubInfos.size()=0
10-20 14:38:50.885 D/NetworkSettings(2147): initializeSubscriptions: DO_NOTHING
10-20 14:38:50.885 D/NetworkSettings(2147): updatePhone:- slotId=1
10-20 14:38:50.889 D/NetworkSettings(2147): updateBody: isLteOnCdma=false phoneSubId=2
10-20 14:38:50.980 D/NetworkSettings(2147): isWorldMode=false
10-20 14:38:50.980 D/NetworkSettings(2147): settingsNetworkMode: 0
10-20 14:38:50.996 D/NetworkSettings(2147): initializeSubscriptions:-
10-20 14:38:50.998 D/NetworkSettings(2147): onCreate:-
10-20 14:38:51.004 D/NetworkSettings(2147): onResume:+
10-20 14:38:51.051 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:38:51.058 D/NetworkSettings(2147): onResume:-
10-20 14:38:51.074 D/NetworkSettings(2147): onSubscriptionsChanged:
10-20 14:38:51.098 D/NetworkSettings(2147): onSubscriptionsChanged: newSil: [{id=2, iccId=895060110XXXXXXXXXXX simSlotIndex=1 displayName=Kolbi ICE carrierName=Kolbi ICE nameSource=2 iconTint=-3851991 dataRoaming=0 iconBitmap=android.graphics.Bitmap@e04788b mcc 712 mnc 1 mUserNwMode=0}] mActiveSubInfos: [{id=2, iccId=895060110XXXXXXXXXXX simSlotIndex=1 displayName=Kolbi ICE carrierName=Kolbi ICE nameSource=2 iconTint=-3851991 dataRoaming=0 iconBitmap=android.graphics.Bitmap@1a8bd7f mcc 712 mnc 1 mUserNwMode=0}]
10-20 14:38:51.098 D/NetworkSettings(2147): onSubscriptionsChanged: Slot matched SimSlotIndex: 1
10-20 14:38:53.481 D/NetworkSettings(2147): onPreferenceChange
10-20 14:38:53.482 D/NetworkSettings(2147): buttonNetworkMode: 1
10-20 14:38:53.533 D/NetworkSettings(2147): handleSetPreferredNetworkTypeResponse: exception in setting network mode.
10-20 14:38:53.558 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:38:55.746 D/NetworkSettings(2147): onPreferenceChange
10-20 14:38:55.750 D/NetworkSettings(2147): buttonNetworkMode: 1
10-20 14:38:55.796 D/NetworkSettings(2147): handleSetPreferredNetworkTypeResponse: exception in setting network mode.
10-20 14:38:55.819 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:38:58.647 D/NetworkSettings(2147): onPause:+
10-20 14:38:58.650 D/NetworkSettings(2147): onPause:-
10-20 14:40:01.575 I/ActivityManager(856): START u0 {cmp=com.android.phone/.MobileNetworkSettings (has extras)} from uid 1000 on display 0
10-20 14:40:01.622 D/NetworkSettings(2147): onCreate:+
10-20 14:40:01.711 D/NetworkSettings(2147): initializeSubscriptions:+
10-20 14:40:01.737 D/NetworkSettings(2147): isUpdateTabsNeeded:- DO_NOTHING newSil.size()=1 mActiveSubInfos.size()=0
10-20 14:40:01.737 D/NetworkSettings(2147): initializeSubscriptions: DO_NOTHING
10-20 14:40:01.737 D/NetworkSettings(2147): updatePhone:- slotId=1
10-20 14:40:01.738 D/NetworkSettings(2147): updateBody: isLteOnCdma=false phoneSubId=2
10-20 14:40:01.804 D/NetworkSettings(2147): isWorldMode=false
10-20 14:40:01.804 D/NetworkSettings(2147): settingsNetworkMode: 0
10-20 14:40:01.811 D/NetworkSettings(2147): initializeSubscriptions:-
10-20 14:40:01.813 D/NetworkSettings(2147): onCreate:-
10-20 14:40:01.817 D/NetworkSettings(2147): onResume:+
10-20 14:40:01.867 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:40:01.872 D/NetworkSettings(2147): onResume:-
10-20 14:40:01.887 D/NetworkSettings(2147): onSubscriptionsChanged:
10-20 14:40:01.912 D/NetworkSettings(2147): onSubscriptionsChanged: newSil: [{id=2, iccId=895060110XXXXXXXXXXX simSlotIndex=1 displayName=Kolbi ICE carrierName=Kolbi ICE nameSource=2 iconTint=-3851991 dataRoaming=0 iconBitmap=android.graphics.Bitmap@ff5ad9a mcc 712 mnc 1 mUserNwMode=0}] mActiveSubInfos: [{id=2, iccId=895060110XXXXXXXXXXX simSlotIndex=1 displayName=Kolbi ICE carrierName=Kolbi ICE nameSource=2 iconTint=-3851991 dataRoaming=0 iconBitmap=android.graphics.Bitmap@37cd7bf mcc 712 mnc 1 mUserNwMode=0}]
10-20 14:40:01.913 D/NetworkSettings(2147): onSubscriptionsChanged: Slot matched SimSlotIndex: 1
10-20 14:40:03.701 D/NetworkSettings(2147): onPreferenceChange
10-20 14:40:03.702 D/NetworkSettings(2147): buttonNetworkMode: 1
10-20 14:40:03.775 D/NetworkSettings(2147): handleSetPreferredNetworkTypeResponse: exception in setting network mode.
10-20 14:40:03.800 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:40:05.147 D/NetworkSettings(2147): onPause:+
10-20 14:40:05.150 D/NetworkSettings(2147): onPause:-
10-20 14:41:04.781 D/NetworkSettings(2147): onResume:+
10-20 14:41:04.876 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:41:04.884 D/NetworkSettings(2147): onResume:-
10-20 14:41:04.955 D/NetworkSettings(2147): onSubscriptionsChanged:
10-20 14:41:04.989 D/NetworkSettings(2147): onSubscriptionsChanged: newSil: [{id=2, iccId=895060110XXXXXXXXXXX simSlotIndex=1 displayName=Kolbi ICE carrierName=Kolbi ICE nameSource=2 iconTint=-3851991 dataRoaming=0 iconBitmap=android.graphics.Bitmap@ed49ef1 mcc 712 mnc 1 mUserNwMode=0}] mActiveSubInfos: [{id=2, iccId=895060110XXXXXXXXXXX simSlotIndex=1 displayName=Kolbi ICE carrierName=Kolbi ICE nameSource=2 iconTint=-3851991 dataRoaming=0 iconBitmap=android.graphics.Bitmap@37cd7bf mcc 712 mnc 1 mUserNwMode=0}]
10-20 14:41:04.990 D/NetworkSettings(2147): onSubscriptionsChanged: Slot matched SimSlotIndex: 1
10-20 14:41:12.175 D/NetworkSettings(2147): onPreferenceChange
10-20 14:41:12.179 D/NetworkSettings(2147): buttonNetworkMode: 1
10-20 14:41:12.222 D/NetworkSettings(2147): handleSetPreferredNetworkTypeResponse: exception in setting network mode.
10-20 14:41:12.249 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:41:13.973 D/NetworkSettings(2147): onPreferenceChange
10-20 14:41:13.974 D/NetworkSettings(2147): buttonNetworkMode: 1
10-20 14:41:14.029 D/NetworkSettings(2147): handleSetPreferredNetworkTypeResponse: exception in setting network mode.
10-20 14:41:14.056 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:41:15.475 D/NetworkSettings(2147): onPause:+
10-20 14:41:15.477 D/NetworkSettings(2147): onPause:-
10-20 14:44:16.695 I/ActivityManager(856): START u0 {cmp=com.android.phone/.MobileNetworkSettings (has extras)} from uid 1000 on display 0
10-20 14:44:16.784 D/NetworkSettings(2147): onCreate:+
10-20 14:44:16.899 D/NetworkSettings(2147): initializeSubscriptions:+
10-20 14:44:16.929 D/NetworkSettings(2147): isUpdateTabsNeeded:- DO_NOTHING newSil.size()=1 mActiveSubInfos.size()=0
10-20 14:44:16.929 D/NetworkSettings(2147): initializeSubscriptions: DO_NOTHING
10-20 14:44:16.929 D/NetworkSettings(2147): updatePhone:- slotId=1
10-20 14:44:16.930 D/NetworkSettings(2147): updateBody: isLteOnCdma=false phoneSubId=2
10-20 14:44:16.998 D/NetworkSettings(2147): isWorldMode=false
10-20 14:44:16.998 D/NetworkSettings(2147): settingsNetworkMode: 0
10-20 14:44:17.005 D/NetworkSettings(2147): initializeSubscriptions:-
10-20 14:44:17.007 D/NetworkSettings(2147): onCreate:-
10-20 14:44:17.011 D/NetworkSettings(2147): onResume:+
10-20 14:44:17.062 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:44:17.068 D/NetworkSettings(2147): onResume:-
10-20 14:44:17.078 D/NetworkSettings(2147): onSubscriptionsChanged:
10-20 14:44:17.104 D/NetworkSettings(2147): onSubscriptionsChanged: newSil: [{id=2, iccId=895060110XXXXXXXXXXX simSlotIndex=1 displayName=Kolbi ICE carrierName=Kolbi ICE nameSource=2 iconTint=-3851991 dataRoaming=0 iconBitmap=android.graphics.Bitmap@719889a mcc 712 mnc 1 mUserNwMode=0}] mActiveSubInfos: [{id=2, iccId=895060110XXXXXXXXXXX simSlotIndex=1 displayName=Kolbi ICE carrierName=Kolbi ICE nameSource=2 iconTint=-3851991 dataRoaming=0 iconBitmap=android.graphics.Bitmap@c8366bf mcc 712 mnc 1 mUserNwMode=0}]
10-20 14:44:17.105 D/NetworkSettings(2147): onSubscriptionsChanged: Slot matched SimSlotIndex: 1
10-20 14:44:17.285 I/ActivityManager(856): Displayed com.android.phone/.MobileNetworkSettings: +527ms
10-20 14:44:19.021 D/NetworkSettings(2147): onPreferenceChange
10-20 14:44:19.022 D/NetworkSettings(2147): buttonNetworkMode: 1
10-20 14:44:19.067 D/NetworkSettings(2147): handleSetPreferredNetworkTypeResponse: exception in setting network mode.
10-20 14:44:19.094 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:44:21.663 D/NetworkSettings(2147): onPreferenceChange
10-20 14:44:21.664 D/NetworkSettings(2147): buttonNetworkMode: 1
10-20 14:44:21.708 D/NetworkSettings(2147): handleSetPreferredNetworkTypeResponse: exception in setting network mode.
10-20 14:44:21.734 D/NetworkSettings(2147): updatePreferredNetworkUIFromDb: settingsNetworkMode = 0
10-20 14:44:22.412 D/NetworkSettings(2147): onPause:+
10-20 14:44:22.415 D/NetworkSettings(2147): onPause:-

**Comment by diepquynh** [comment]
Confirmed

**Comment by diepquynh** [comment]
Cleaned RIL class, solved the issue
